'use client';
import {useEffect,useRef,useState} from 'react';
import {DISTRICTS,districtById} from './districts';
import {KERALA_VIEWBOX,KERALA_DISTRICT_PATHS,KERALA_DISTRICT_CENTER} from './kerala-map';
export type FreeBus={id:string;district:string;driver?:string};
export function DistrictAtlas({open,onClose,onTravel,ready,visited,current,buses=[]}:{open:boolean;onClose:()=>void;onTravel:(id:string)=>boolean;ready:boolean;visited:string[];current:string|null;buses?:FreeBus[]}){
 const dialog=useRef<HTMLDialogElement>(null);const [selected,setSelected]=useState('alappuzha'),[query,setQuery]=useState(''),[error,setError]=useState('');const district=districtById(selected)!;
 useEffect(()=>{const el=dialog.current;if(open&&!el?.open)el?.showModal();else if(!open&&el?.open)el.close()},[open]);
 const filtered=DISTRICTS.filter(d=>(d.name+' '+d.malayalam).toLowerCase().includes(query.toLowerCase()));
 return <dialog ref={dialog} className="district-atlas" data-atlas aria-labelledby="atlas-title" onCancel={onClose} onClose={onClose} onKeyDown={e=>e.stopPropagation()}>
 <div className="atlas-heading"><div><p className="atlas-eyebrow">THE NEXT CHAPTER</p><h2 id="atlas-title">One Kerala. Fourteen journeys.</h2><p>{visited.length} / 14 gateways visited</p></div><button className="atlas-close" onClick={onClose} aria-label="Close district atlas">×</button></div>
 <div className="atlas-body"><div className="atlas-map"><svg viewBox={KERALA_VIEWBOX.join(' ')} role="img" aria-label="Map of Kerala's 14 districts, north at the top"><text x={KERALA_VIEWBOX[2]*.05} y={KERALA_VIEWBOX[3]*.52} fill="#8fb8a6" fontSize="7" transform={`rotate(-90 ${KERALA_VIEWBOX[2]*.05} ${KERALA_VIEWBOX[3]*.52})`}>ARABIAN SEA</text><text x={KERALA_VIEWBOX[2]-22} y="15" fill="#d9e8b7" fontSize="10">N ↑</text>{DISTRICTS.map(d=>KERALA_DISTRICT_PATHS[d.id]&&<path key={d.id} d={KERALA_DISTRICT_PATHS[d.id]} onClick={()=>{setSelected(d.id);setError('')}} style={{cursor:'pointer'}} fill={selected===d.id?'#d3e58e':current===d.id?'#bfd889':visited.includes(d.id)?'#5f9c7e':'#274b3f'} fillOpacity={selected===d.id?1:.92} stroke="#9db98b" strokeWidth={selected===d.id?1.1:.5}><title>{d.name}</title></path>)}{DISTRICTS.map((d,i)=>{const c=KERALA_DISTRICT_CENTER[d.id];return c?<text key={d.id} x={c[0]} y={c[1]+2.5} textAnchor="middle" fontSize="7.5" fontWeight="600" fill={selected===d.id?'#183a30':'#eef3dd'} style={{pointerEvents:'none'}}>{i+1}</text>:null})}{Object.entries(buses.reduce((a,b)=>{a[b.district]=(a[b.district]||0)+1;return a},{} as Record<string,number>)).map(([id,n])=>{const c=KERALA_DISTRICT_CENTER[id];return c?<g key={id} style={{pointerEvents:'none'}}><circle cx={c[0]+7} cy={c[1]-6} r="4.5" fill="#f6c65a" stroke="#5b3a12" strokeWidth=".7"/><text x={c[0]+7} y={c[1]-3.7} textAnchor="middle" fontSize="6" fontWeight="700" fill="#5b3a12">{n}</text></g>:null})}</svg><p>Real Kerala geography · CC BY 4.0 DataMeet{buses.length?` · 🚌 ${buses.length} free bus${buses.length>1?'es':''} parked`:''}</p></div>
 <div className="atlas-districts"><label htmlFor="district-search">Find your district</label><input id="district-search" type="search" placeholder="Search district…" value={query} onChange={e=>setQuery(e.target.value)}/><div className="atlas-list" aria-label="Districts">{filtered.map((d)=><button key={d.id} aria-pressed={selected===d.id} onClick={()=>{setSelected(d.id);setError('')}}><span>{d.name}<small lang="ml">{d.malayalam}</small></span><span aria-label={visited.includes(d.id)?'Visited gateway':'Unvisited gateway'}>{visited.includes(d.id)?'✓':'↗'}</span></button>)}{!filtered.length&&<p>No district found.</p>}</div></div>
 <section className="atlas-detail" aria-live="polite"><p className="atlas-eyebrow">{current===district.id?'CURRENT GATEWAY':'DISTRICT PREVIEW'}</p><h3>{district.name}</h3><p lang="ml">{district.malayalam}</p><p>{district.landscape}</p><div className="atlas-plan"><strong>Discovery spots</strong>{district.stops.map(s=><span key={s}>{s}</span>)}<strong>Signature festival</strong><span>{district.festival}</span></div><p className="atlas-note">Every district now has its own landmark and discovery spots to find — drive there across the loop or travel through the gateway. Festivals and live events are still upcoming.</p><button className="atlas-travel" disabled={!ready} onClick={()=>{if(onTravel(district.id)){setError('');onClose()}else setError('This gateway is blocked. Choose another gateway and try again.')}}>{ready?'Drive from this gateway →':'Preparing the bus…'}</button>{error&&<p role="alert">{error}</p>}<a href="https://www.keralatourism.org/districts/" target="_blank" rel="noreferrer">Explore district references ↗</a></section></div>
 </dialog>;
}
