'use client';
import {useEffect,useRef,useState} from 'react';
import {DISTRICTS,districtById} from './districts';
export function DistrictAtlas({open,onClose,onTravel,ready,visited,current}:{open:boolean;onClose:()=>void;onTravel:(id:string)=>boolean;ready:boolean;visited:string[];current:string|null}){
 const dialog=useRef<HTMLDialogElement>(null);const [selected,setSelected]=useState('alappuzha'),[query,setQuery]=useState(''),[error,setError]=useState('');const district=districtById(selected)!;
 useEffect(()=>{const el=dialog.current;if(open&&!el?.open)el?.showModal();else if(!open&&el?.open)el.close()},[open]);
 const filtered=DISTRICTS.filter(d=>(d.name+' '+d.malayalam).toLowerCase().includes(query.toLowerCase()));
 return <dialog ref={dialog} className="district-atlas" data-atlas aria-labelledby="atlas-title" onCancel={onClose} onClose={onClose} onKeyDown={e=>e.stopPropagation()}>
 <div className="atlas-heading"><div><p className="atlas-eyebrow">THE NEXT CHAPTER</p><h2 id="atlas-title">One Kerala. Fourteen journeys.</h2><p>{visited.length} / 14 gateways visited</p></div><button className="atlas-close" onClick={onClose} aria-label="Close district atlas">×</button></div>
 <div className="atlas-body"><div className="atlas-map"><svg viewBox="0 0 340 540" role="img" aria-label="Schematic map of Kerala district locations, north at the top"><path d="M30 10 C67 13 117 49 163 65 L191 80 225 164 290 205 319 290 304 369 284 445 261 516 229 487 214 447 182 409 172 363 161 321 146 281 137 237 113 203 96 174 69 136 49 99 25 58 Z" fill="#315847" stroke="#aac18c" strokeWidth="1.2"/><text x="16" y="292" fill="#afcbb8" fontSize="10" transform="rotate(-72 16 292)">ARABIAN SEA</text><text x="299" y="37" fill="#d9e8b7" fontSize="13">N ↑</text>{DISTRICTS.flatMap(d=>d.neighbors.filter(n=>n>d.id).map(id=>{const other=districtById(id)!;return <line key={d.id+id} x1={d.map[0]} y1={d.map[1]} x2={other.map[0]} y2={other.map[1]} stroke="#a5bd8866" strokeDasharray="3 4"/>}))}{DISTRICTS.map((d,i)=><g key={d.id} onClick={()=>{setSelected(d.id);setError('')}} style={{cursor:'pointer'}}><circle cx={d.map[0]} cy={d.map[1]} r={selected===d.id?14:10} fill={selected===d.id?'#d3e58e':visited.includes(d.id)?'#85b69a':'#173d34'} stroke="#d3e58e"/><text x={d.map[0]} y={d.map[1]+4} textAnchor="middle" fontSize="10" fill={selected===d.id?'#183a30':'#f3f4de'}>{i+1}</text></g>)}</svg><p>Schematic geography · gateways currently connect to the village loop.</p></div>
 <div className="atlas-districts"><label htmlFor="district-search">Find your district</label><input id="district-search" type="search" placeholder="Search district…" value={query} onChange={e=>setQuery(e.target.value)}/><div className="atlas-list" aria-label="Districts">{filtered.map((d)=><button key={d.id} aria-pressed={selected===d.id} onClick={()=>{setSelected(d.id);setError('')}}><span>{d.name}<small lang="ml">{d.malayalam}</small></span><span aria-label={visited.includes(d.id)?'Visited gateway':'Unvisited gateway'}>{visited.includes(d.id)?'✓':'↗'}</span></button>)}{!filtered.length&&<p>No district found.</p>}</div></div>
 <section className="atlas-detail" aria-live="polite"><p className="atlas-eyebrow">{current===district.id?'CURRENT GATEWAY':'DISTRICT PREVIEW'}</p><h3>{district.name}</h3><p lang="ml">{district.malayalam}</p><p>{district.landscape}</p><div className="atlas-plan"><strong>Discovery spots</strong>{district.stops.map(s=><span key={s}>{s}</span>)}<strong>Signature festival</strong><span>{district.festival}</span></div><p className="atlas-note">Every district now has its own landmark and discovery spots to find — drive there across the loop or travel through the gateway. Festivals and live events are still upcoming.</p><button className="atlas-travel" disabled={!ready} onClick={()=>{if(onTravel(district.id)){setError('');onClose()}else setError('This gateway is blocked. Choose another gateway and try again.')}}>{ready?'Drive from this gateway →':'Preparing the bus…'}</button>{error&&<p role="alert">{error}</p>}<a href="https://www.keralatourism.org/districts/" target="_blank" rel="noreferrer">Explore district references ↗</a></section></div>
 </dialog>;
}
