'use client';
import { useEffect, useRef, useState } from 'react';
import { Pause, Play, RotateCcw, Focus, Globe2, MoveUpRight, Sun, Sunset } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { createPlanet } from './planet';
export default function Home(){
 const host=useRef<HTMLDivElement>(null);const engine=useRef<ReturnType<typeof createPlanet>|null>(null);const [ready,setReady]=useState(false);const [error,setError]=useState('');const [playing,setPlaying]=useState(true);const [follow,setFollow]=useState(false);const [evening,setEvening]=useState(false);
 useEffect(()=>{if(!host.current)return;if(matchMedia('(prefers-reduced-motion: reduce)').matches)setPlaying(false);try{engine.current=createPlanet(host.current,()=>setReady(true),(msg)=>setError(msg));}catch{setError('Your browser could not start the 3D view. Please try a browser with WebGL enabled.');}return()=>engine.current?.dispose();},[]);
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options:{signal:AbortSignal})=>unknown}}).modelContext;if(!context)return;const lifecycle=new AbortController();try{Promise.resolve(context.registerTool({name:'configure_planet',description:'Set the bus playback, follow camera, and time of day in Little Kerala.',inputSchema:{type:'object',properties:{playing:{type:'boolean'},follow:{type:'boolean'},sunset:{type:'boolean'}},additionalProperties:false},execute:(input:unknown)=>{if(!input||typeof input!=='object')throw new Error('Expected settings');const v=input as Record<string,unknown>;for(const k of Object.keys(v))if(!['playing','follow','sunset'].includes(k)||typeof v[k]!=='boolean')throw new Error('Invalid setting');if(typeof v.playing==='boolean'){setPlaying(v.playing);engine.current?.play(v.playing)}if(typeof v.follow==='boolean'){setFollow(v.follow);engine.current?.follow(v.follow)}if(typeof v.sunset==='boolean'){setEvening(v.sunset);engine.current?.light(v.sunset)}return {applied:v}},annotations:{readOnlyHint:false,untrustedContentHint:false}},{signal:lifecycle.signal})).catch(()=>{});}catch{}return()=>lifecycle.abort();},[]);
 return <main className="experience"><div ref={host} className="world" aria-label="Interactive miniature Kerala planet. Drag to orbit and scroll to zoom." role="img"/><header><a className="brand" href="/" aria-label="Little Kerala home"><Globe2 size={25}/><span>LITTLE KERALA</span></a><span className="edition">A WORLD OF OUR OWN <span>01 / KERALA</span></span></header><section className="intro"><p className="eyebrow"><span/> A LITTLE WORLD, ALWAYS MOVING</p><h1>Home, in<br/><i>its own orbit.</i></h1><p className="description">A red bus. Coconut groves. The long way home.<br/>Take a little trip around Kerala.</p><div className="coordinate">9.9312° N &nbsp; 76.2673° E <MoveUpRight size={14}/></div></section><div className="side-label">GOD’S OWN LITTLE PLANET</div>{!ready&&!error&&<div className="loading" role="status">Bringing the village to life…</div>}{error&&<div className="loading error" role="alert">{error}</div>}<div className="bus-card"><span className="route-number">KSRTC</span><div><strong>The village loop</strong><span>{playing?'On the move':'Taking a little break'} · Fast Passenger</span></div><span className={'live '+(!playing?'stopped':'')}/></div><footer><div className="instructions"><span className="drag-mark">↔</span><div>Make yourself at home<small>Drag to explore · Scroll or pinch to zoom</small></div></div><nav className="controls" aria-label="Planet controls"><Button variant="ghost" aria-label={playing?'Pause bus':'Play bus'} onClick={()=>{setPlaying(!playing);engine.current?.play(!playing)}}>{playing?<Pause size={18}/>:<Play size={18}/>}<span>{playing?'Pause':'Play'}</span></Button><Button variant="ghost" aria-pressed={follow} onClick={()=>{setFollow(!follow);engine.current?.follow(!follow)}}><Focus size={18}/><span>Follow bus</span></Button><Button variant="ghost" aria-label={evening?'Use noon sunlight':'Use sunset lighting'} onClick={()=>{setEvening(!evening);engine.current?.light(!evening)}}>{evening?<Sunset size={18}/>:<Sun size={18}/>}<span>{evening?'Sunset':'Noon'}</span></Button><Button variant="ghost" aria-label="Reset view" onClick={()=>{engine.current?.reset();setFollow(false)}}><RotateCcw size={18}/></Button></nav></footer></main>
}
