import * as T from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
export function createPlanet(host:HTMLDivElement,onReady:()=>void,onError:(s:string)=>void){
 const scene=new T.Scene();const renderer=new T.WebGLRenderer({antialias:true,alpha:true});renderer.setPixelRatio(Math.min(window.devicePixelRatio,1.6));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFSoftShadowMap;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.25;host.appendChild(renderer.domElement);
 const camera=new T.PerspectiveCamera(39,1,.1,180);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=10;controls.maxDistance=35;controls.autoRotate=false;
 const globe=new T.Group();scene.add(globe);globe.rotation.z=-.19;const R=5.6;
 const mat=(color:number,roughness=.9)=>new T.MeshStandardMaterial({color,roughness});const green=mat(0x698d3f),palmGreen=mat(0x326739),leafLight=mat(0x649340),trunk=mat(0x816446),roof=mat(0xac5031),cream=mat(0xe9d6a3),blue=mat(0x304f52),asphalt=mat(0x494f49),soil=mat(0xae7850),white=mat(0xdddbb5);
 const sphere=new T.Mesh(new T.IcosahedronGeometry(R,5),green);sphere.receiveShadow=true;globe.add(sphere);
 const sun=new T.DirectionalLight(0xfff0ce,3.7);sun.position.set(-8,16,9);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);sun.shadow.camera.left=-10;sun.shadow.camera.right=10;sun.shadow.camera.top=10;sun.shadow.camera.bottom=-10;sun.shadow.normalBias=.045;scene.add(sun);const hemi=new T.HemisphereLight(0xc4e4eb,0x33552c,2.1);scene.add(hemi);
 const pos=(t:number,lat:number,r=R)=>new T.Vector3(Math.cos(t)*Math.cos(lat),Math.sin(lat),Math.sin(t)*Math.cos(lat)).multiplyScalar(r);
 const latitude=(t:number)=>.17+.10*Math.sin(t*3)+.05*Math.cos(t*2);
 const point=(t:number,r=R+.027)=>pos(t,latitude(t),r);
 const attach=(obj:T.Object3D,t:number,lat:number,r=R)=>{const p=pos(t,lat,r);obj.position.copy(p);obj.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),p.clone().normalize());globe.add(obj);return obj};
 const mesh=(geo:T.BufferGeometry,m:T.Material,parent:T.Object3D,x=0,y=0,z=0)=>{const o=new T.Mesh(geo,m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o};
 function band(width:number,r:number,m:T.Material){const v:number[]=[],idx:number[]=[];for(let i=0;i<=320;i++){const t=i/320*Math.PI*2;for(const d of [-width/2,width/2])v.push(...pos(t,latitude(t)+d/R,r).toArray());if(i<320){const k=i*2;idx.push(k,k+2,k+1,k+1,k+2,k+3)}}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(v,3));g.setIndex(idx);g.computeVertexNormals();const o=mesh(g,m,globe);o.material.side=T.DoubleSide;return o}
 band(1.24,R+.035,soil);band(1.03,R+.052,asphalt);
 for(let i=0;i<80;i++){const t=i/80*Math.PI*2;const p=point(t,R+.061);const d=point(t+.003).sub(point(t)).normalize();const o=new T.Mesh(new T.BoxGeometry(.14,.005,.024),white);o.position.copy(p);o.quaternion.setFromRotationMatrix(new T.Matrix4().makeBasis(d,p.clone().normalize(),new T.Vector3().crossVectors(d,p).normalize()));globe.add(o)}
 let seed=81;const rnd=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};
 const leafGeo=(()=>{const verts:number[]=[],ids:number[]=[];for(let j=0;j<=12;j++){const t=j/12;const w=Math.sin(Math.PI*t)*.17;verts.push(t*1.05,.34*Math.sin(t*Math.PI)-.25*t,-w,t*1.05,.34*Math.sin(t*Math.PI)-.25*t,w);if(j<12){const k=j*2;ids.push(k,k+1,k+2,k+1,k+3,k+2)}}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(verts,3));g.setIndex(ids);g.computeVertexNormals();return g})();palmGreen.side=T.DoubleSide;leafLight.side=T.DoubleSide;
 function palm(t:number,lat:number,size:number){const g=new T.Group();attach(g,t,lat);g.scale.setScalar(size);const curve=new T.QuadraticBezierCurve3(new T.Vector3(),new T.Vector3(.08,.8,0),new T.Vector3(.28,1.55,0));mesh(new T.TubeGeometry(curve,8,.047,6,false),trunk,g);for(let i=0;i<9;i++){const leaf=mesh(leafGeo,i%3===0?leafLight:palmGreen,g,.28,1.54,0);leaf.rotation.y=i*Math.PI*2/9;leaf.rotation.z=.05+rnd()*.3}for(let i=0;i<3;i++)mesh(new T.SphereGeometry(.068,6,5),trunk,g,.23+i*.065,1.48,.055)}
 for(let i=0;i<63;i++){const t=rnd()*Math.PI*2;const lat=latitude(t)+(rnd()>.5?1:-1)*(.19+rnd()*.46);palm(t,lat,.65+rnd()*.48)}
 function house(t:number,lat:number,i:number){const g=new T.Group();attach(g,t,lat);g.rotateY(rnd()*Math.PI);const w=.7+rnd()*.22,d=.65;mesh(new T.BoxGeometry(w,.52,d),i%3===0?mat(0xc3d1af):cream,g,0,.26,0);const rg=new T.BufferGeometry();rg.setAttribute('position',new T.Float32BufferAttribute([-w*.6,.52,-d*.6,w*.6,.52,-d*.6,0,.88,-d*.6,-w*.6,.52,d*.6,w*.6,.52,d*.6,0,.88,d*.6],3));rg.setIndex([0,2,1,3,4,5,0,3,5,0,5,2,2,5,4,2,4,1]);rg.computeVertexNormals();mesh(rg,roof,g);mesh(new T.BoxGeometry(.17,.32,.015),blue,g,.05,.16,d/2+.009);for(const x of [-.24,.25])mesh(new T.BoxGeometry(.12,.14,.02),blue,g,x,.33,d/2+.01);mesh(new T.BoxGeometry(w+.18,.05,.27),cream,g,0,.03,d/2+.10);for(const x of [-w*.47,w*.47])mesh(new T.CylinderGeometry(.019,.019,.48,6),cream,g,x,.26,d/2+.20)}
 for(let i=0;i<20;i++){const t=i/20*Math.PI*2;house(t,latitude(t)+(i%2?1:-1)*(.27+rnd()*.15),i)}
 for(let i=0;i<40;i++){const t=rnd()*Math.PI*2,lat=(rnd()-.5)*2.8;if(Math.abs(lat-latitude(t))<.4)continue;const g=new T.Group();attach(g,t,lat);mesh(new T.CylinderGeometry(.025,.045,.34,5),trunk,g,0,.17,0);const crown=mesh(new T.IcosahedronGeometry(.28+rnd()*.13,1),i%2?leafLight:palmGreen,g,0,.47,0);crown.scale.y=1.3}
 // Small terrain mounds and a backwater pond follow the globe surface.
 const pond=new T.Mesh(new T.SphereGeometry(1,32,16),new T.MeshStandardMaterial({color:0x3c9791,roughness:.22,metalness:.22}));pond.scale.set(1.0,.05,.65);attach(pond,2.3,.95,R+.005);
 for(let i=0;i<60;i++){const t=rnd()*Math.PI*2,lat=(rnd()-.5)*Math.PI;if(Math.abs(lat-latitude(t))<.15)continue;const stone=new T.Mesh(new T.IcosahedronGeometry(.05+rnd()*.07,0),mat(0x8a9170));attach(stone,t,lat,R+.025)}
 const bus=new T.Group();globe.add(bus);let loaded=false,disposed=false;
 new GLTFLoader().load('/ksrtc.glb',(gltf)=>{if(disposed)return;const model=gltf.scene;model.scale.setScalar(.17);model.traverse(o=>{if(o instanceof T.Mesh){o.castShadow=true;o.receiveShadow=true}});bus.add(model);loaded=true;onReady()},undefined,()=>onError('The bus could not load. Refresh to try again.'));
 let playing=!matchMedia('(prefers-reduced-motion: reduce)').matches,follow=false,angle=.7,frame=0,last=performance.now();
 const home=()=>{const mobile=host.clientWidth<850;camera.position.set(15,11,19).multiplyScalar(mobile?1.12:1);controls.target.set(mobile?0:-2.7,mobile?1.7:.3,0);controls.update()};
 const resize=()=>{renderer.setSize(host.clientWidth,host.clientHeight);camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix()};const observer=new ResizeObserver(resize);observer.observe(host);resize();home();
 function animate(now:number){if(disposed)return;frame=requestAnimationFrame(animate);const dt=Math.min((now-last)/1000,.05);last=now;if(playing)angle+=dt*.105;const p=point(angle,R+.08);const up=p.clone().normalize();const x=point(angle+.001).sub(point(angle)).normalize();const z=new T.Vector3().crossVectors(x,up).normalize();const y=new T.Vector3().crossVectors(z,x).normalize();bus.position.copy(p);bus.quaternion.setFromRotationMatrix(new T.Matrix4().makeBasis(x,y,z));if(follow&&loaded){const target=bus.getWorldPosition(new T.Vector3());controls.target.lerp(target,.06);const desired=target.clone().multiplyScalar(1.95).add(new T.Vector3(2,2,3));camera.position.lerp(desired,.025)}controls.update();renderer.render(scene,camera)}frame=requestAnimationFrame(animate);
 return {play:(v:boolean)=>{playing=v},follow:(v:boolean)=>{follow=v;if(!v)controls.target.set(0,0,0)},light:(v:boolean)=>{sun.color.set(v?0xffa14c:0xfff0ce);sun.intensity=v?3:3.7;hemi.intensity=v?1.1:2.1;sun.position.set(-8,v?3:16,9)},reset:()=>{follow=false;home()},dispose:()=>{disposed=true;cancelAnimationFrame(frame);observer.disconnect();controls.dispose();scene.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>m.dispose())}});renderer.dispose();renderer.domElement.remove()}};
}
