import {coastalTerrain,addWorldDetails} from './world-details';
import {WORLD_RADIUS,ROAD_ROUTES,ROAD_DASHES,roadJunction,roadLatitude,roadOffset,isDryLand,terrainElevation} from './world';
import {DISTRICTS,districtById,gatewayAt} from './districts';
import {createDistrictGateways} from './district-gateways';
import {createDistrictScenery} from './district-scenery';
import {NATURAL_PALETTE as palette} from './natural-palette';
import * as T from 'three';
import {createBusAudio} from './bus-audio';
import {createSuspension} from './suspension';
import {createVehicleGround} from './vehicle-ground';
import {createBusContactShadow} from './bus-shadows';
import {createPedestrians} from './pedestrians';
import {gradeGreenTerrain} from './green-terrain';
import {batchStaticMeshes} from './batch-meshes';
import {createDayLighting,type TimeOfDay} from './lighting';
import {createVillageBackground} from './background';
export const SCENE_REVISION='kerala-anatomical-human-20260911';
import { clearTreesFromHomes } from './tree-placement';
import { createRoadSurface } from './road-surface';
import { createPond } from './pond';
import { addUtilities } from './utilities';
import { createBirds } from './birds';
import { createWheelRoll } from './wheels';
import { createHouseFactory } from './houses';
import { addLandscape } from './landscape';
import { intersectsBus,moveWithCollisions,contactRadius,surfaceRadius,type Obstacle } from './vehicle-physics';
import { positionDriverCamera } from './fpv-camera';
import { createRoadView } from './road-view';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import { GLTFLoader } from 'three/examples/jsm/loaders/GLTFLoader.js';
import { createWalker,findSpawn } from './player-character';
import { createAvatar } from './player-avatar';
import { outfitForName } from './multiplayer-math';
import { createMultiplayer } from './multiplayer';
import { createVoiceChat,type VoiceState,type VoiceMsg } from './voice';
import { isMultiplayerConfigured, getPlayerId } from './realtime';
import { createBusFleet, depotFootprint } from './bus-fleet';
import { createBusNet, type Occupant } from './bus-net';
export type BusHudState={near:number|null;driving:number|null;occupancy:{bus:number;name:string}[]};
export function createPlanet(host:HTMLDivElement,onReady:()=>void,onError:(s:string)=>void,onDrive:()=>void=()=>{},onDistrict:(id:string)=>void=()=>{},onRoster:(names:string[])=>void=()=>{},onVoice:(state:VoiceState)=>void=()=>{},onBus:(s:BusHudState)=>void=()=>{}){
 // Low-power tier (phones / touch / few-core machines): lighter render target, smaller shadow map, fewer props.
 // Cuts the biggest GPU costs so the little planet stays smooth on mobile without changing the desktop look.
 const lowPower=(typeof matchMedia!=='undefined'&&matchMedia('(pointer: coarse)').matches)||window.innerWidth<850||(navigator.hardwareConcurrency||8)<=4;
 const audio=createBusAudio();const scene=new T.Scene();const villageBackground=createVillageBackground();scene.background=villageBackground;scene.backgroundIntensity=1;let pendingModels=3;const modelReady=()=>{pendingModels--;if(pendingModels===0&&!disposed)onReady()};const renderer=new T.WebGLRenderer({antialias:!lowPower,alpha:true});renderer.setPixelRatio(Math.min(window.devicePixelRatio,lowPower?1.25:1.6));renderer.shadowMap.enabled=true;renderer.shadowMap.type=T.PCFShadowMap;renderer.shadowMap.autoUpdate=false;let lastShadow=0;renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;renderer.toneMappingExposure=1.35;host.appendChild(renderer.domElement);
 const camera=new T.PerspectiveCamera(39,1,.1,180);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=12;controls.maxDistance=55;controls.autoRotate=false;
 const globe=new T.Group();scene.add(globe);globe.rotation.z=-.19;const R=WORLD_RADIUS;const obstacles:Obstacle[]=[];const homeFootprints:Obstacle[]=[];const windPlants:T.Group[]=[];
 const mat=(color:number,roughness=.9)=>new T.MeshStandardMaterial({color,roughness});const green=mat(0x698d3f),palmGreen=mat(0x477c3c),leafLight=mat(0x71a34e),trunk=mat(0x816446),roof=mat(0xac5031),cream=mat(0xe9d6a3),blue=mat(0x304f52),asphalt=mat(0x494f49),soil=mat(0xae7850),white=mat(0xdddbb5);
 const groundGeo=new T.SphereGeometry(R,lowPower?176:288,lowPower?112:192);const gp=groundGeo.attributes.position;const colors=[];for(let i=0;i<gp.count;i++){const x=gp.getX(i),y=gp.getY(i),z=gp.getZ(i);const t=Math.atan2(z,x),lat=Math.asin(y/R),radial=R+terrainElevation(t,lat);gp.setXYZ(i,x*radial/R,y*radial/R,z*radial/R);const noise=Math.sin(x*18+y*23)*Math.sin(z*29+x*9)*.06+Math.sin(x*3+z*5)*Math.sin(y*4-z*2)*.09;const c=new T.Color(palette.groundTint).multiplyScalar(1+noise);colors.push(c.r,c.g,c.b)}groundGeo.setAttribute('color',new T.Float32BufferAttribute(colors,3));green.vertexColors=true;green.color.set(0xffffff);const groundLoader=new T.TextureLoader();const groundTexture=groundLoader.load("/textures/aerial_grass_rock_diff_1k.jpg");groundTexture.colorSpace=T.SRGBColorSpace;groundTexture.wrapS=groundTexture.wrapT=T.RepeatWrapping;groundTexture.repeat.set(14,7);groundTexture.anisotropy=4;green.map=groundTexture;gradeGreenTerrain(green);coastalTerrain(green);const sphere=new T.Mesh(groundGeo,green);sphere.receiveShadow=true;globe.add(sphere);
 const sun=new T.DirectionalLight(0xfff0ce,3.7);sun.position.set(-8,16,9);sun.castShadow=true;sun.shadow.mapSize.set(lowPower?1024:2048,lowPower?1024:2048);sun.shadow.camera.left=-6.5;sun.shadow.camera.right=6.5;sun.shadow.camera.top=6.5;sun.shadow.camera.bottom=-6.5;sun.shadow.camera.near=.5;sun.shadow.camera.far=46;sun.shadow.bias=-.00008;sun.shadow.normalBias=.001;sun.shadow.camera.updateProjectionMatrix();scene.add(sun);scene.add(sun.target);const shadowFocus=new T.Vector3();const hemi=new T.HemisphereLight(0xdceef5,0x91a18b,2.6);scene.add(hemi);const ambient=new T.AmbientLight(0xfffaf2,.55);scene.add(ambient);
 const pos=(t:number,lat:number,r=R)=>new T.Vector3(Math.cos(t)*Math.cos(lat),Math.sin(lat),Math.sin(t)*Math.cos(lat)).multiplyScalar(r);
 const latitude=(t:number)=>roadLatitude(t);
 const point=(t:number,r=R+.027)=>pos(t,latitude(t),r);
 // Reserve a clear patch for the KSRTC bus stand: nothing procedural spawns inside its footprint.
 const depotFP=depotFootprint(pos);const inDepot=(n:T.Vector3)=>Math.acos(T.MathUtils.clamp(n.dot(depotFP.center),-1,1))*R<depotFP.radius;
 // The depot is built after the districts, so reserve its footprint up front as a placement-only obstacle
 // (disabled → ignored by driving collision) — keeps district scenery/landscape from spawning on the stand.
 obstacles.push({normal:depotFP.center,radius:depotFP.radius,disabled:true});
 const attach=(obj:T.Object3D,t:number,lat:number,r=R)=>{const p=pos(t,lat,r);obj.position.copy(p);obj.quaternion.setFromUnitVectors(new T.Vector3(0,1,0),p.clone().normalize());globe.add(obj);return obj};
 const mesh=(geo:T.BufferGeometry,m:T.Material,parent:T.Object3D,x=0,y=0,z=0)=>{const o=new T.Mesh(geo,m);o.position.set(x,y,z);o.castShadow=true;o.receiveShadow=true;parent.add(o);return o};
 function band(width:number,r:number,m:T.Material){const v:number[]=[],idx:number[]=[];for(let i=0;i<=320;i++){const t=i/320*Math.PI*2;for(const d of [-width/2,width/2])v.push(...pos(t,latitude(t)+d/R,r).toArray());if(i<320){const k=i*2;idx.push(k,k+2,k+1,k+1,k+2,k+3)}}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(v,3));g.setIndex(idx);g.computeVertexNormals();const o=mesh(g,m,globe);o.material.side=T.DoubleSide;return o}
 globe.add(createRoadSurface(pos,latitude));
 // Lane dashes: one shared box merged into a single draw instead of ~400 individual meshes.
 const dashGroup=new T.Group();dashGroup.name='Lane markings';const dashGeo=new T.BoxGeometry(.14,.002,.024);
 for(const route of ROAD_ROUTES)for(let i=0;i<ROAD_DASHES;i++){const t=i/ROAD_DASHES*Math.PI*2;if(roadJunction(t,route))continue;const p=pos(t,roadLatitude(t,route),R+.055+route*.0001);const d=pos(t+.003,roadLatitude(t+.003,route)).sub(pos(t,roadLatitude(t,route))).normalize();const o=new T.Mesh(dashGeo,white);o.position.copy(p);o.quaternion.setFromRotationMatrix(new T.Matrix4().makeBasis(d,p.clone().normalize(),new T.Vector3().crossVectors(d,p).normalize()));dashGroup.add(o)}
 batchStaticMeshes(dashGroup);globe.add(dashGroup);
 let seed=81;const rnd=()=>{seed=(seed*1664525+1013904223)>>>0;return seed/4294967296};
 const leafGeo=(()=>{const verts:number[]=[],ids:number[]=[];for(let j=0;j<=12;j++){const t=j/12;const w=Math.sin(Math.PI*t)*.17;verts.push(t*1.05,.34*Math.sin(t*Math.PI)-.25*t,-w,t*1.05,.34*Math.sin(t*Math.PI)-.25*t,w);if(j<12){const k=j*2;ids.push(k,k+1,k+2,k+1,k+3,k+2)}}const g=new T.BufferGeometry();g.setAttribute('position',new T.Float32BufferAttribute(verts,3));g.setIndex(ids);g.computeVertexNormals();return g})();palmGreen.side=T.DoubleSide;leafLight.side=T.DoubleSide;
 function palm(t:number,lat:number,size:number){const g=new T.Group();g.name="palm-placeholder";attach(g,t,lat);g.scale.setScalar(size);g.userData.wind=true;windPlants.push(g);obstacles.push({normal:g.position.clone().normalize(),radius:.14*size});const curve=new T.QuadraticBezierCurve3(new T.Vector3(),new T.Vector3(.08,.8,0),new T.Vector3(.28,1.55,0));mesh(new T.TubeGeometry(curve,8,.047,6,false),trunk,g);for(let i=0;i<9;i++){const leaf=mesh(leafGeo,i%3===0?leafLight:palmGreen,g,.28,1.54,0);leaf.rotation.y=i*Math.PI*2/9;leaf.rotation.z=.05+rnd()*.3}for(let i=0;i<3;i++)mesh(new T.SphereGeometry(.068,6,5),trunk,g,.23+i*.065,1.48,.055)}
 for(let i=0;i<(lowPower?56:100);i++){const t=rnd()*Math.PI*2;const lat=-.70+rnd()*1.95;if(!isDryLand(t,lat)||roadOffset(t,lat)<.92||inDepot(pos(t,lat).normalize()))continue;palm(t,lat,.60+rnd()*.52)}
 const buildHouse=createHouseFactory();
 function house(t:number,lat:number,i:number){const {group:g,halfX,halfZ}=buildHouse(i);attach(g,t,lat);const up=g.position.clone().normalize();const front=point(t).sub(g.position).projectOnPlane(up).normalize();const right=new T.Vector3().crossVectors(up,front).normalize();g.quaternion.setFromRotationMatrix(new T.Matrix4().makeBasis(right,up,front));const footprint={normal:up,axis:right,halfX,halfZ};obstacles.push(footprint);homeFootprints.push(footprint)}
 for(let i=0;i<(lowPower?45:70);i++){const t=(Math.floor(i/5)/14*Math.PI*2)+(i%5-2)*.045;const route=Math.floor(i/5)%3;const lat=roadLatitude(t,route)+(i%2?1:-1)*(.145+rnd()*.09);const n=pos(t,lat).normalize();if(!isDryLand(t,lat)||roadOffset(t,lat)<1.15||inDepot(n)||obstacles.some(o=>Math.acos(T.MathUtils.clamp(n.dot(o.normal),-1,1))*R<(o.radius??Math.hypot(o.halfX??0,o.halfZ??0))+.85))continue;house(t,lat,i)}
 for(let i=0;i<(lowPower?60:110);i++){const t=rnd()*Math.PI*2,lat=-.6+rnd()*2.0;if(!isDryLand(t,lat)||roadOffset(t,lat)<1.05||inDepot(pos(t,lat).normalize()))continue;const g=new T.Group();g.name='tree-placeholder';attach(g,t,lat);g.userData.wind=true;windPlants.push(g);obstacles.push({normal:g.position.clone().normalize(),radius:.11});mesh(new T.CylinderGeometry(.025,.045,.34,5),trunk,g,0,.17,0);const crown=mesh(new T.IcosahedronGeometry(.28+rnd()*.13,1),i%2?leafLight:palmGreen,g,0,.47,0);crown.scale.y=1.3}
 // Small terrain mounds and a backwater pond follow the globe surface.
 const pond=createPond(globe,groundGeo);
 const terrainRocks:T.Group[]=[];for(let i=0;i<(lowPower?54:84);i++){const t=rnd()*Math.PI*2,roadside=i>=60,lat=roadside?latitude(t)+(i%2?1:-1)*((.68+rnd()*.24)/R):(rnd()-.5)*Math.PI;if(!isDryLand(t,lat)||(!roadside&&roadOffset(t,lat)<.8)||inDepot(pos(t,lat).normalize()))continue;const group=new T.Group();group.name='Grounded road stone';const size=roadside?.018+rnd()*.02:.05+rnd()*.07;const stone=new T.Mesh(new T.IcosahedronGeometry(size,2),mat(0x73776c));stone.castShadow=stone.receiveShadow=true;stone.scale.y=roadside?.65:1;group.add(stone);const n=pos(t,lat,R).normalize();attach(group,t,lat,surfaceRadius(n)+(roadside?.002:.025));terrainRocks.push(group)}
 clearTreesFromHomes(globe,homeFootprints,obstacles,latitude);
 const landscape=addLandscape(globe,obstacles,latitude);const birds=createBirds(globe);const utilities=addUtilities(globe,obstacles,latitude,lowPower?8:12);
 const plantLoader=new GLTFLoader();for(const kind of ['palm','tree'])plantLoader.load('/'+kind+'.glb',gltf=>{if(disposed)return;const bounds=new T.Box3().setFromObject(gltf.scene);const size=bounds.getSize(new T.Vector3());const center=bounds.getCenter(new T.Vector3());const leafMaterials=new Set<T.MeshStandardMaterial>();gltf.scene.traverse(o=>{if(o instanceof T.Mesh)for(const material of Array.isArray(o.material)?o.material:[o.material])if(material instanceof T.MeshStandardMaterial&&/leaf|leaves/i.test(material.name))leafMaterials.add(material)});for(const material of leafMaterials){material.color.set(0xc7e7bd);material.roughness=.88;material.metalness=0;material.emissive.set(0x000000);material.emissiveIntensity=0;material.needsUpdate=true;}batchStaticMeshes(gltf.scene);const normalized=new T.Group();gltf.scene.position.set(-center.x,-bounds.min.y,-center.z);normalized.add(gltf.scene);normalized.scale.setScalar((kind==='palm'?1.65:.9)/size.y);gltf.scene.traverse(o=>{if(o instanceof T.Mesh){o.castShadow=true;o.receiveShadow=true}});for(const old of [...globe.children])if(old.name===kind+'-placeholder'){const replacement=new T.Group();replacement.position.copy(old.position);replacement.quaternion.copy(old.quaternion);replacement.scale.copy(old.scale);replacement.userData.wind=true;windPlants.push(replacement);const plantModel=normalized.clone(true);const variation=(salt:number)=>{const v=Math.sin(old.position.x*127.1+old.position.y*311.7+old.position.z*74.7+salt)*43758.5453;return v-Math.floor(v)};plantModel.rotation.set((variation(1)-.5)*(kind==='palm'?.16:.06),variation(2)*Math.PI*2,(variation(3)-.5)*(kind==='palm'?.16:.06));plantModel.scale.multiply(new T.Vector3(.88+variation(4)*.24,.90+variation(5)*.20,.88+variation(6)*.24));replacement.add(plantModel);globe.add(replacement);globe.remove(old)}modelReady()},undefined,()=>{modelReady()});
 const expandedWorld=addWorldDetails(globe,obstacles,inDepot);const districtGateways=createDistrictGateways(globe,point,latitude,obstacles);const districtScenery=createDistrictScenery(globe,obstacles,latitude);const pedestrians=createPedestrians(globe,obstacles,latitude,lowPower?5:8);/* Clear any scenery (e.g. a district coconut palm) that landed inside the KSRTC bus stand footprint. */globe.updateMatrixWorld(true);{const standR=2.5,inStand=(n:T.Vector3)=>Math.acos(T.MathUtils.clamp(n.dot(depotFP.center),-1,1))*R<standR,pw=new T.Vector3(),prune:T.Object3D[]=[];globe.traverse(o=>{if(o!==globe&&(o.userData.wind||o.userData.dyn)){o.getWorldPosition(pw);if(inStand(pw.clone().normalize()))prune.push(o)}});for(const o of prune){o.parent?.remove(o);const wi=windPlants.indexOf(o as T.Group);if(wi>=0)windPlants.splice(wi,1)}for(let i=obstacles.length-1;i>=0;i--){if(!obstacles[i].disabled&&inStand(obstacles[i].normal))obstacles.splice(i,1)}}let currentGateway:string|undefined;
 // Shared KSRTC bus stand: four parked buses anyone can board and drive, synced live over one global channel.
 const localId=getPlayerId();const busFleet=createBusFleet(globe,pos,obstacles);
 let myBus=-1,nearBus:number|null=null,busDriving=false,currentName='';let busOccupancy=new Map<number,Occupant>();const parkedBuses=new Set<number>();
 const emitBus=()=>onBus({near:nearBus,driving:busDriving?myBus:null,occupancy:[...busOccupancy].map(([bus,v])=>({bus,name:v.name}))});
 const busNet=isMultiplayerConfigured()?createBusNet({playerId:localId,onOccupancy:occ=>{busOccupancy=occ;emitBus()},onYield:()=>{if(busDriving)exitBus()}}):undefined;busNet?.connect();
 const glassMeshes:T.Mesh[]=[];const bus=new T.Group();globe.add(bus);const busContactShadow=createBusContactShadow(bus);let loaded=false,disposed=false;let wheelRoll:ReturnType<typeof createWheelRoll>|undefined;let suspension:ReturnType<typeof createSuspension>|undefined;let coach:T.Object3D|undefined;const vehicleGround=createVehicleGround(globe,terrainRocks);const roadView=createRoadView(scene,globe,bus,point,latitude,pos);const dayLighting=createDayLighting(scene,camera,renderer,sun,hemi,ambient,bus);let trackTop=false,trackChase=false;
 new GLTFLoader().load('/ksrtc.glb',(gltf)=>{if(disposed)return;const model=gltf.scene;model.scale.setScalar(.17);model.traverse(o=>{if(o instanceof T.Mesh){o.castShadow=true;o.receiveShadow=true;const materials=Array.isArray(o.material)?o.material:[o.material];if(materials.some(m=>/Coach red enamel|Classic golden yellow|Weathered grey shutter metal/.test(m.name)))o.receiveShadow=false;if(materials.some(m=>/glass|glazing/i.test(m.name))){o.material=new T.MeshStandardMaterial({name:'Clear browser window glass',color:0xc5e3df,transparent:true,opacity:.07,roughness:.12,metalness:0,depthWrite:false,side:T.DoubleSide});o.castShadow=false;o.receiveShadow=false;glassMeshes.push(o);o.visible=!inside;}}});bus.add(model);dayLighting.registerBus(model);batchStaticMeshes(model,mesh=>{if(glassMeshes.includes(mesh))return true;let parent:T.Object3D|null=mesh;while(parent&&parent!==model){if(/^(Front|Rear)[ _]wheel[ _]axle/i.test(parent.name))return true;parent=parent.parent}return false});wheelRoll=createWheelRoll(model);coach=model;suspension=createSuspension(wheelRoll.supports);loaded=true;modelReady()},undefined,()=>onError('The bus could not load. Refresh to try again.'));
 let orbitYaw=0,orbitElevation=1.50,orbitDistance=10.5;let activeLookPointer:number|null=null;let inside=false,lookYaw=0,lookPitch=-.15,looking=false,lookX=0,lookY=0;let driving=false;let walking=false,trackWalk=false,walkMoving=false;let walker:ReturnType<typeof createWalker>|undefined,localAvatar:ReturnType<typeof createAvatar>|undefined,mp:ReturnType<typeof createMultiplayer>|undefined,voice:ReturnType<typeof createVoiceChat>|undefined;const characterBlockers:Obstacle[]=[];const remoteAvatars=new Map<string,ReturnType<typeof createAvatar>>();let lastVoiceProx=0;const voicePeers=new Map<string,T.Vector3>();let voiceSpeaking=new Set<string>(),voiceLocalSpeaking=false;const held=new Set<string>();const driveState={normal:point(.7).normalize(),heading:point(.701).sub(point(.7)).normalize(),speed:0,steering:0,waterResistance:0,lateralSpeed:0,collisionYaw:0,collisionImpact:undefined as {speed:number;forward:number;lateral:number}|undefined};
 // Avatar level-of-detail: frame cost must not scale with crowd size. Only the nearest few are fully animated,
 // a wider ring is drawn (throttled animation), and everyone beyond is hidden — so 300 people cost like ~40.
 let lodTick=0;const AVATAR_ANIM_CAP=14,AVATAR_RENDER_CAP=44;
 const crowdBots:{avatar:ReturnType<typeof createAvatar>;n:T.Vector3;axis:T.Vector3;speed:number}[]=[];
 const lodList:{a:ReturnType<typeof createAvatar>;n:T.Vector3;moving:boolean;d:number}[]=[];
 const applyAvatarLOD=(dt:number,localN:T.Vector3)=>{
  for(const it of lodList)it.d=Math.acos(T.MathUtils.clamp(localN.dot(it.n),-1,1));
  lodList.sort((a,b)=>a.d-b.d);lodTick++;
  for(let i=0;i<lodList.length;i++){const it=lodList[i],vis=i<AVATAR_RENDER_CAP;it.a.group.visible=vis;if(!vis)continue;if(i<AVATAR_ANIM_CAP)it.a.update(dt,it.moving);else if((lodTick+i)%4===0)it.a.update(dt*4,it.moving)}
  lodList.length=0;
 };
 // Dev/load-test only (?bots=N): synthetic walkers drifting on great circles, to measure the LOD under a crowd.
 const spawnCrowdBots=(count:number)=>{for(let i=0;i<count;i++){const a=createAvatar({name:'Visitor '+(i+1),gender:i%2,outfit:i%3,label:i<24});a.group.userData.avatar=true;globe.add(a.group);const n=new T.Vector3(Math.sin(i*2.3999)*Math.cos(i*1.1),Math.sin(i*0.7)*.9,Math.cos(i*2.3999)*Math.cos(i*1.1)).normalize(),axis=new T.Vector3(Math.cos(i*1.7),Math.sin(i*0.9)+.3,Math.sin(i*2.1)).normalize();crowdBots.push({avatar:a,n,axis,speed:.03+(i%6)*.015})}};
 let playing=!matchMedia('(prefers-reduced-motion: reduce)').matches,follow=false,angle=.7,frame=0,last=performance.now();
 const home=()=>{controls.enabled=true;camera.up.set(0,1,0);const mobile=host.clientWidth<850;camera.position.set(15,11,19).multiplyScalar((R/5.6)*(mobile?1.12:1));controls.target.set(mobile?0:-4.3,mobile?2.7:.5,0);controls.update()};
 const resize=()=>{renderer.setSize(host.clientWidth,host.clientHeight);camera.aspect=host.clientWidth/host.clientHeight;camera.updateProjectionMatrix()};const observer=new ResizeObserver(resize);observer.observe(host);resize();home();
 const updateFollowCamera=(followed:T.Object3D,lift=0)=>{followed.updateWorldMatrix(true,false);const q=followed.getWorldQuaternion(new T.Quaternion());const target=followed.getWorldPosition(new T.Vector3()).add(new T.Vector3(0,lift,0).applyQuaternion(q));const horizontal=Math.cos(orbitElevation)*orbitDistance;camera.position.copy(followed.localToWorld(new T.Vector3(-Math.cos(orbitYaw)*horizontal,Math.sin(orbitElevation)*orbitDistance,Math.sin(orbitYaw)*horizontal)));camera.up.set(0,1,0).applyQuaternion(q);camera.lookAt(target);controls.target.copy(target)};
 const topDrivingView=()=>{orbitYaw=0;orbitElevation=1.50;orbitDistance=10.5;trackChase=false;inside=false;roadView.setVisible(false);scene.fog=null;trackTop=true;glassMeshes.forEach(o=>{o.visible=true});scene.background=villageBackground;controls.enabled=false;controls.autoRotate=false;camera.fov=48;camera.near=.1;camera.updateProjectionMatrix();updateFollowCamera(bus);follow=false;};
 const startDrive=()=>{dropBus();if(!driving){walking=false;trackWalk=false;driveState.normal.copy(bus.position).normalize();driveState.heading.set(1,0,0).applyQuaternion(bus.quaternion);driveState.speed=0;driveState.steering=0;driveState.waterResistance=0;driveState.lateralSpeed=0;driveState.collisionYaw=0;driving=true;topDrivingView();onDrive()}};
 const setFPV=(enabled:boolean)=>{trackChase=false;inside=enabled;glassMeshes.forEach(o=>{o.visible=!enabled});scene.background=villageBackground;looking=false;lookYaw=0;lookPitch=-.15;controls.enabled=!enabled;camera.fov=enabled?84:39;camera.near=enabled?.005:.1;camera.updateProjectionMatrix();if(enabled){startDrive();inside=true;trackTop=false;roadView.setVisible(true);scene.fog=new T.Fog(0x1a4140,9,30);glassMeshes.forEach(o=>{o.visible=false});scene.background=villageBackground;controls.enabled=false;camera.fov=84;camera.near=.005;camera.updateProjectionMatrix();follow=false}else{roadView.setVisible(false);scene.fog=null;topDrivingView()}};
 const chaseDrivingView=()=>{startDrive();orbitYaw=.15;orbitElevation=.54;orbitDistance=4;inside=false;trackTop=false;trackChase=true;follow=false;roadView.setVisible(false);scene.background=villageBackground;scene.fog=null;glassMeshes.forEach(o=>{o.visible=true});controls.enabled=false;camera.fov=55;camera.near=.02;camera.updateProjectionMatrix()};
 const walkView=()=>{dropBus();if(!localAvatar)return;driving=false;inside=false;trackTop=false;trackChase=false;follow=false;looking=false;roadView.setVisible(false);scene.fog=null;glassMeshes.forEach(o=>{o.visible=true});scene.background=villageBackground;controls.enabled=false;controls.autoRotate=false;orbitYaw=0;orbitElevation=.42;orbitDistance=2.6;camera.fov=55;camera.near=.02;camera.updateProjectionMatrix();driveState.speed=0;driveState.steering=0;held.clear();walking=true;trackWalk=true};
 // Chase camera for a shared fleet bus (a driving sub-mode of walk: you keep your villager, but ride the coach).
 const busDriveView=()=>{driving=false;walking=false;trackWalk=false;inside=false;trackTop=false;trackChase=false;follow=false;looking=false;roadView.setVisible(false);scene.fog=null;glassMeshes.forEach(o=>{o.visible=true});scene.background=villageBackground;controls.enabled=false;controls.autoRotate=false;orbitYaw=.15;orbitElevation=.5;orbitDistance=4.6;camera.fov=55;camera.near=.02;camera.updateProjectionMatrix()};
 function dropBus(){if(myBus>=0||busDriving){busNet?.release();myBus=-1;busDriving=false;emitBus()}}
 function boardBus(){if(myBus>=0||nearBus===null||!walker||!localAvatar)return;const id=nearBus;parkedBuses.delete(id);const holder=busOccupancy.get(id);if(holder&&holder.id!==localId)return;myBus=id;busDriving=true;walking=false;trackWalk=false;held.clear();busNet?.claim(id,currentName);busDriveView();emitBus()}
 function exitBus(){if(myBus<0)return;const id=myBus;const b=busFleet.buses[id];parkedBuses.add(id);b.state.speed=0;if(walker){const rgt=new T.Vector3().crossVectors(b.state.heading,b.state.normal).normalize();const axis=new T.Vector3().crossVectors(b.state.normal,rgt).normalize();const out=b.state.normal.clone().applyQuaternion(new T.Quaternion().setFromAxisAngle(axis,.95/R)).normalize();walker.state.normal.copy(out);walker.state.heading.copy(b.state.heading).addScaledVector(out,-b.state.heading.dot(out)).normalize()}dropBus();walkView()}
 const startWalk=(id:string,name:string,gender:number)=>{currentName=name;if(localAvatar){walkView();return}const outfit=outfitForName(name);walker=createWalker(findSpawn(id,[...obstacles,{normal:bus.position.clone().normalize(),radius:1}]),obstacles,characterBlockers);localAvatar=createAvatar({name,gender,outfit,label:false});localAvatar.group.userData.avatar=true;globe.add(localAvatar.group);walkView();if(isMultiplayerConfigured()){voice=createVoiceChat({playerId:id,send:(to,msg)=>mp?.signalVoice(to,msg),onState:s=>{voiceSpeaking=new Set(s.speaking);voiceLocalSpeaking=s.localSpeaking;onVoice(s)}});mp=createMultiplayer({playerId:id,name,gender,outfit,onJoin:(rid,meta)=>{if(disposed||remoteAvatars.has(rid))return;const avatar=createAvatar({name:meta.name,gender:meta.gender,outfit:meta.outfit,label:true});avatar.group.visible=false;avatar.group.userData.avatar=true;remoteAvatars.set(rid,avatar);globe.add(avatar.group)},onLeave:rid=>{remoteAvatars.get(rid)?.dispose();remoteAvatars.delete(rid);voice?.removePeer(rid)},onRoster,onVoice:(from,msg)=>voice?.handleSignal(from,msg as VoiceMsg)});mp.connect()}
  try{const nb=Number(new URLSearchParams(location.search).get('bots'))||0;if(nb>0&&!crowdBots.length)spawnCrowdBots(Math.min(nb,600))}catch{}};
 const lookStart=(e:PointerEvent)=>{if(e.button!==0||activeLookPointer!==null||!(inside||(driving&&(trackTop||trackChase))||(walking&&trackWalk)||busDriving))return;activeLookPointer=e.pointerId;looking=true;lookX=e.clientX;lookY=e.clientY;renderer.domElement.setPointerCapture(e.pointerId)};
 const lookMove=(e:PointerEvent)=>{if(!looking||e.pointerId!==activeLookPointer)return;const dx=e.clientX-lookX,dy=e.clientY-lookY;if(inside){lookYaw=Math.max(-1.1,Math.min(1.1,lookYaw-dx*.004));lookPitch=Math.max(-.65,Math.min(.3,lookPitch-dy*.004))}else if((driving&&(trackTop||trackChase))||(walking&&trackWalk)||busDriving){orbitYaw-=dx*.005;orbitElevation=Math.max(.15,Math.min(1.50,orbitElevation+dy*.005))}lookX=e.clientX;lookY=e.clientY};
 const lookEnd=()=>{looking=false;activeLookPointer=null};
 const zoomDrive=(e:WheelEvent)=>{const orbitCam=(walking&&trackWalk)||busDriving;if(inside||(!orbitCam&&!(driving&&(trackTop||trackChase))))return;e.preventDefault();const delta=e.deltaY*(e.deltaMode===1?16:e.deltaMode===2?host.clientHeight:1);const next=orbitDistance*Math.exp(Math.max(-1,Math.min(1,delta*.001)));orbitDistance=orbitCam?Math.max(1.2,Math.min(9,next)):Math.max(2.5,Math.min(18,next))};
 renderer.domElement.addEventListener('pointerdown',lookStart);renderer.domElement.addEventListener('pointermove',lookMove);renderer.domElement.addEventListener('pointerup',lookEnd);renderer.domElement.addEventListener('pointercancel',lookEnd);renderer.domElement.addEventListener('lostpointercapture',lookEnd);renderer.domElement.addEventListener('wheel',zoomDrive,{passive:false});

 const keys:Record<string,string>={ArrowUp:'forward',w:'forward',ArrowDown:'reverse',s:'reverse',ArrowLeft:'left',a:'left',ArrowRight:'right',d:'right'};
 const down=(e:KeyboardEvent)=>{const k=keys[e.key]||keys[e.key.toLowerCase()];if(k&&!(e.target instanceof HTMLInputElement)){e.preventDefault();if(!walking&&!busDriving)startDrive();held.add(k)}};
 const up=(e:KeyboardEvent)=>{const k=keys[e.key]||keys[e.key.toLowerCase()];if(k){e.preventDefault();held.delete(k)}};const clear=()=>held.clear();window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',clear);
 const visitDistrict=(id:string)=>{const d=districtById(id);if(!d||!loaded)return false;let spawn:number|undefined;for(let i=0;i<25;i++){const t=d.gateway+(i%2?1:-1)*Math.ceil(i/2)*.009,n=point(t).normalize(),heading=point(t+.001).sub(point(t)).projectOnPlane(n).normalize();if(!intersectsBus({normal:n,heading,speed:0,steering:0},obstacles)){spawn=t;break}}if(spawn===undefined)return false;
  held.clear();angle=spawn;driveState.normal.copy(point(spawn)).normalize();driveState.heading.copy(point(spawn+.001).sub(point(spawn))).projectOnPlane(driveState.normal).normalize();driveState.speed=driveState.steering=driveState.lateralSpeed=driveState.collisionYaw=driveState.waterResistance=0;driveState.collisionImpact=undefined;
  bus.position.copy(driveState.normal).multiplyScalar(R);const right=new T.Vector3().crossVectors(driveState.heading,driveState.normal);bus.quaternion.setFromRotationMatrix(new T.Matrix4().makeBasis(driveState.heading,driveState.normal,right));suspension=wheelRoll?createSuspension(wheelRoll.supports):undefined;bus.userData.previousVerticalVelocity=0;driving=true;topDrivingView();onDrive();currentGateway=d.id;onDistrict(d.id);return true;
 };
 function animate(now:number){if(disposed)return;frame=requestAnimationFrame(animate);const dt=Math.min((now-last)/1000,.05);last=now;landscape.update(now);expandedWorld.update(now);districtScenery.update(now);pond.update(now,sun,bus);birds.update(now*.001);pedestrians.update(dt,bus.position);if(playing&&!driving)angle+=dt*.59/R;const p=point(angle);p.normalize().multiplyScalar(R);const up=p.clone().normalize();const x=point(angle+.001).sub(point(angle)).normalize();const z=new T.Vector3().crossVectors(x,up).normalize();const y=new T.Vector3().crossVectors(z,x).normalize();if(driving){const collided=moveWithCollisions(driveState,(held.has('forward')?1:0)-(held.has('reverse')?1:0),(held.has('left')?1:0)-(held.has('right')?1:0),dt,obstacles);if(collided&&driveState.collisionImpact){const impact=driveState.collisionImpact;audio.crash(impact.speed);suspension?.impact(impact.forward,impact.lateral);}p.copy(driveState.normal).multiplyScalar(R);x.copy(driveState.heading);y.copy(driveState.normal);z.crossVectors(x,y).normalize()}
 characterBlockers.length=0;
 if(mp)for(const r of mp.remotes.values()){const sample=mp.sample(r,now);if(sample)characterBlockers.push({normal:sample.normal,radius:.05});}
 for(const b of busFleet.buses)characterBlockers.push({normal:b.state.normal.clone(),radius:.95});
 characterBlockers.push({normal:bus.position.clone().normalize(),radius:.95}); // the player's own bus is solid to walkers too, so you never spawn/stand inside it
 walkMoving=walking&&walker?walker.update(dt,{forward:held.has('forward'),reverse:held.has('reverse'),left:held.has('left'),right:held.has('right')}):false;
 if(walker&&localAvatar){let wn=walker.state.normal,wf=walker.state.heading,mv=walkMoving;if(busDriving&&myBus>=0){const b=busFleet.buses[myBus];walker.state.normal.copy(b.state.normal);walker.state.heading.copy(b.state.heading);wn=walker.state.normal;wf=walker.state.heading;mv=Math.abs(b.state.speed)>.03}const wr=new T.Vector3().crossVectors(wf,wn).normalize();localAvatar.group.position.copy(wn).multiplyScalar(surfaceRadius(wn)+.001);localAvatar.group.quaternion.setFromRotationMatrix(new T.Matrix4().makeBasis(wf,wn,wr));localAvatar.update(dt,mv);mp?.send(wn,wf,mv)}
 if(mp){voicePeers.clear();for(const [rid,r] of mp.remotes){const avatar=remoteAvatars.get(rid);if(!avatar)continue;const s=mp.sample(r,now);if(!s)continue;const rr=new T.Vector3().crossVectors(s.heading,s.normal).normalize();avatar.group.position.copy(s.normal).multiplyScalar(surfaceRadius(s.normal)+.001);avatar.group.quaternion.setFromRotationMatrix(new T.Matrix4().makeBasis(s.heading,s.normal,rr));avatar.setSpeaking?.(voiceSpeaking.has(rid));voicePeers.set(rid,s.normal.clone());lodList.push({a:avatar,n:s.normal,moving:s.moving,d:0})}
  // Proximity for voice: feed the local + remote normals a few times a second so gains/connections track distance.
  if(voice&&walker&&voice.isEnabled()&&now-lastVoiceProx>180){lastVoiceProx=now;voice.updateProximity(walker.state.normal,voicePeers)}}
  for(const bot of crowdBots){bot.n.applyAxisAngle(bot.axis,bot.speed*dt);const n=bot.n,heading=new T.Vector3().crossVectors(bot.axis,n).normalize(),rr=new T.Vector3().crossVectors(heading,n).normalize();bot.avatar.group.position.copy(n).multiplyScalar(surfaceRadius(n)+.001);bot.avatar.group.quaternion.setFromRotationMatrix(new T.Matrix4().makeBasis(heading,n,rr));lodList.push({a:bot.avatar,n,moving:true,d:0})}
  if(lodList.length)applyAvatarLOD(dt,walker?walker.state.normal:bus.position.clone().normalize());
  localAvatar?.setSpeaking?.(voiceLocalSpeaking);
 // Shared fleet: drive the one I claimed, replay the ones others drive, ease idle buses back to their bay.
 for(const b of busFleet.buses){
  if(b.id===myBus){const thr=(held.has('forward')?1:0)-(held.has('reverse')?1:0),stw=(held.has('left')?1:0)-(held.has('right')?1:0);busFleet.stepLocal(b.id,thr,stw,dt,obstacles);busFleet.place(b.id);busNet?.sendBus(b.id,b.state.normal,b.state.heading,Math.abs(b.state.speed)>.03)}
  else if(busOccupancy.has(b.id)&&busNet){const s=busNet.sample(b.id,now);if(s)busFleet.setTransform(b.id,s.normal,s.heading);busFleet.place(b.id)}
  else if(parkedBuses.has(b.id)){busFleet.place(b.id)}else{busFleet.returnToBay(b.id,dt);busFleet.place(b.id)}
 }
 if(walking&&walker&&myBus<0){const nb=busFleet.boardable(walker.state.normal,busOccupancy,localId);if(nb!==nearBus){nearBus=nb;emitBus()}}
 else if(myBus<0&&nearBus!==null){nearBus=null;emitBus()}
 for(let i=0;i<windPlants.length;i++){const plant=windPlants[i];if(plant.parent!==globe||!plant.visible)continue;const sway=Math.sin(now*.0015+i*2.1)*.018+Math.sin(now*.0031+i)*.006;const base=new T.Quaternion().setFromUnitVectors(new T.Vector3(0,1,0),plant.position.clone().normalize());plant.quaternion.copy(base).multiply(new T.Quaternion().setFromAxisAngle(new T.Vector3(0,0,1),sway))}const movement=p.clone().sub(bus.position);const previousHeading=new T.Vector3(1,0,0).applyQuaternion(bus.quaternion).projectOnPlane(y).normalize();const headingChange=Math.atan2(new T.Vector3().crossVectors(previousHeading,x).dot(y),previousHeading.dot(x));const steeringAngle=driving?driveState.steering:(movement.length()>1e-5&&movement.length()<.25?Math.atan(1.0115*headingChange/movement.length()):0);wheelRoll?.setSteering(steeringAngle,dt,driving);if(bus.position.lengthSq()>1&&movement.length()<.25){const distance=bus.position.clone().normalize().angleTo(p.clone().normalize())*surfaceRadius(p.clone().normalize());wheelRoll?.advance(distance*Math.sign(movement.dot(x)))}bus.position.copy(p);bus.quaternion.setFromRotationMatrix(new T.Matrix4().makeBasis(x,y,z));if(wheelRoll&&suspension&&coach){const ground=vehicleGround.sample(bus,wheelRoll.supports,inside);const water=vehicleGround.water(bus,wheelRoll.supports,inside);const state=suspension.step(ground,dt,water);driveState.waterResistance=state.immersion.reduce((a,b)=>a+b,0)/state.immersion.length;bus.userData.waterContacts=wheelRoll.supports.map((w,i)=>new T.Vector3(w.x,state.wheelY[i],w.z));coach.position.y=state.height;coach.rotation.set(-state.roll,0,state.pitch,'ZYX');wheelRoll.setSuspension(state.wheelY);bus.userData.suspensionPose={height:state.height,pitch:state.pitch,roll:state.roll};bus.userData.wheelGrounded=state.grounded;bus.userData.suspensionImpact=Math.abs(state.velocity-(bus.userData.previousVerticalVelocity??state.velocity));bus.userData.previousVerticalVelocity=state.velocity;}busContactShadow.update(inside);if((trackTop||trackChase)&&driving&&!inside)updateFollowCamera(bus);else if(busDriving&&myBus>=0)updateFollowCamera(busFleet.buses[myBus].group,.45);else if(walking&&trackWalk&&localAvatar)updateFollowCamera(localAvatar.group,.2);if(follow&&loaded&&!inside&&!driving){const target=bus.getWorldPosition(new T.Vector3());controls.target.lerp(target,.06);const desired=target.clone().multiplyScalar(1.95).add(new T.Vector3(2,2,3));camera.position.lerp(desired,.025)}if(inside&&loaded){roadView.update();positionDriverCamera(camera,bus,lookYaw,lookPitch)}else if(!((trackTop||trackChase)&&driving)&&!(walking&&trackWalk)&&!busDriving)controls.update();dayLighting.update(dt);
 // Keep the shadow frustum tight around the bus: same sun direction, but the ortho box tracks the bus so
 // only nearby scenery is drawn into the shadow map (fewer casters, sharper shadows) instead of the whole hemisphere.
 bus.getWorldPosition(shadowFocus);sun.position.add(shadowFocus);sun.target.position.copy(shadowFocus);sun.target.updateMatrixWorld();
 utilities.update(dayLighting.nightAmount(),bus.position);if(now-lastShadow>(lowPower?66:33)){renderer.shadowMap.needsUpdate=true;lastShadow=now}if(!inside){const viewNormal=globe.worldToLocal(camera.getWorldPosition(new T.Vector3())).normalize();const nearDrive=driving&&(trackTop||trackChase),busNormal=bus.position.clone().normalize();for(const object of globe.children)if(object instanceof T.Group&&object!==bus&&!object.userData.avatar&&object.position.lengthSq()>1){const on=object.position.clone().normalize();object.visible=on.dot(viewNormal)>-.20&&(!nearDrive||on.dot(busNormal)>.34);}}if(loaded){const t=Math.atan2(bus.position.z,bus.position.x),offset=Math.asin(bus.position.clone().normalize().y)-latitude(t),gateway=gatewayAt(t,offset);if(gateway&&gateway.id!==currentGateway){currentGateway=gateway.id;onDistrict(gateway.id)}}audio.update(walking?0:driving?driveState.speed:playing?.59:0,!walking&&driving&&(held.has('forward')||held.has('reverse')),driveState.waterResistance,inside,loaded&&!walking&&(driving||playing),bus.userData.suspensionImpact??0,dayLighting.nightAmount(),loaded);renderer.render(scene,camera)}frame=requestAnimationFrame(animate);
 return {visitDistrict,clearInput:()=>held.clear(),mute:(v:boolean)=>audio.mute(v),volume:(v:number)=>audio.volume(v),horn:()=>audio.horn(),chaseView:chaseDrivingView,topView:()=>{startDrive();topDrivingView()},fpv:setFPV,centerLook:()=>{lookYaw=0;lookPitch=-.15},drive:(direction:string,pressed:boolean)=>{if(pressed){if(!walking&&!busDriving)startDrive();held.add(direction)}else held.delete(direction)},startWalk:(o:{id:string;name:string;gender:number})=>startWalk(o.id,o.name,o.gender),walkView,boardBus:()=>boardBus(),exitBus:()=>exitBus(),voice:(on:boolean)=>{if(on)voice?.enable();else voice?.disable()},voiceTalk:(on:boolean)=>voice?.setTalking(on),voiceBlock:(id:string)=>voice?.block(id),voiceAvailable:()=>Boolean(voice),mode:(manual:boolean)=>{if(manual)startDrive();else{dropBus();driving=false;walking=false;trackWalk=false;held.clear();driveState.speed=0;driveState.steering=0;driveState.waterResistance=0;driveState.lateralSpeed=0;driveState.collisionYaw=0;if(!inside){trackTop=false;trackChase=false;home()}}},play:(v:boolean)=>{playing=v},follow:(v:boolean)=>{if(inside)setFPV(false);follow=v;if(!v)controls.target.set(0,0,0)},hour:(value:number)=>dayLighting.setHour(value),timeOfDay:(mode:TimeOfDay)=>dayLighting.set(mode),light:(v:boolean)=>dayLighting.set(v?'evening':'noon'),reset:()=>{dropBus();if(inside)setFPV(false);trackTop=false;trackChase=false;follow=false;driving=false;walking=false;trackWalk=false;held.clear();angle=.7;driveState.speed=0;driveState.steering=0;driveState.waterResistance=0;driveState.lateralSpeed=0;driveState.collisionYaw=0;suspension=wheelRoll?createSuspension(wheelRoll.supports):undefined;home()},dispose:()=>{disposed=true;busNet?.dispose();busFleet.dispose();voice?.dispose();mp?.dispose();localAvatar?.dispose();remoteAvatars.forEach(a=>a.dispose());remoteAvatars.clear();crowdBots.forEach(b=>b.avatar.dispose());crowdBots.length=0;districtGateways.dispose();districtScenery.dispose();audio.dispose();busContactShadow.dispose();pedestrians.dispose();utilities.dispose();dayLighting.dispose();villageBackground.dispose();pond.dispose();roadView.dispose();renderer.domElement.removeEventListener('pointerdown',lookStart);renderer.domElement.removeEventListener('pointermove',lookMove);renderer.domElement.removeEventListener('pointerup',lookEnd);renderer.domElement.removeEventListener('pointercancel',lookEnd);renderer.domElement.removeEventListener('lostpointercapture',lookEnd);renderer.domElement.removeEventListener('wheel',zoomDrive);window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',clear);cancelAnimationFrame(frame);observer.disconnect();controls.dispose();scene.traverse(o=>{if(o instanceof T.Mesh){o.geometry.dispose();(Array.isArray(o.material)?o.material:[o.material]).forEach(m=>m.dispose())}});renderer.dispose();renderer.domElement.remove()}};
}
