import {WORLD_RADIUS,ROAD_DASHES,ROAD_ROUTES,roadJunction,roadLatitude,terrainElevation,SEA_LEVEL} from './world';
import {NATURAL_PALETTE as palette} from './natural-palette';
import * as T from 'three';
import {clone as cloneRig} from 'three/addons/utils/SkeletonUtils.js';
import {anchorGroundTexture,groundDirection} from './ground-mapping';
import {createRoadSurface} from './road-surface';
import {surfaceRadius} from './vehicle-physics';
// Locally unwrap the little planet for a usable road-level horizon.
export function projectRoadPoint(source:T.Vector3,normal:T.Vector3,forward:T.Vector3,right:T.Vector3,radius=WORLD_RADIUS,originRadius=(WORLD_RADIUS+.052)){
 const radial=source.length(),n=source.clone().normalize(),cos=T.MathUtils.clamp(n.dot(normal),-1,1),angle=Math.acos(cos);
 const tangent=n.addScaledVector(normal,-cos);if(tangent.lengthSq()>1e-12)tangent.normalize().multiplyScalar(angle*radius);
 return new T.Vector3(tangent.dot(forward),radial-originRadius,tangent.dot(right));
}
export function createRoadView(scene:T.Scene,globe:T.Group,bus:T.Group,point:(t:number,r?:number)=>T.Vector3,latitude:(t:number)=>number,pos:(t:number,l:number,r?:number)=>T.Vector3){
 const root=new T.Group();root.visible=false;root.matrixAutoUpdate=false;scene.add(root);
 const groundMap=new T.TextureLoader().load("/textures/aerial_grass_rock_diff_1k.jpg");groundMap.colorSpace=T.SRGBColorSpace;groundMap.wrapS=groundMap.wrapT=T.RepeatWrapping;groundMap.repeat.set(1,1);groundMap.anisotropy=4;
 const ground=new T.Mesh(new T.PlaneGeometry(48,48,64,64),new T.MeshStandardMaterial({color:palette.groundTint,map:groundMap,roughness:1}));ground.rotation.x=-Math.PI/2;ground.position.y=-.052;ground.receiveShadow=true;root.add(ground);const groundMapping=anchorGroundTexture(ground.material);const groundXY=ground.geometry.attributes.position.array.slice();
 const ocean=new T.Mesh(new T.PlaneGeometry(48,48),new T.MeshStandardMaterial({color:0x206e79,roughness:.29,metalness:.25}));ocean.rotation.x=-Math.PI/2;ocean.receiveShadow=true;root.add(ocean);const oceanMapping=anchorGroundTexture(ocean.material,true);
 const road=createRoadSurface(pos,latitude);const geo=road.geometry;const sourceRoad=geo.attributes.position.array.slice();road.frustumCulled=false;root.add(road);
 const markings=new T.Group();root.add(markings);const dashGeo=new T.BoxGeometry(.16,.002,.024),dashMat=new T.MeshStandardMaterial({color:0xe5dfb8});const dashes=Array.from({length:ROAD_DASHES*ROAD_ROUTES.length},()=>{const m=new T.Mesh(dashGeo,dashMat);markings.add(m);return m});
 const syncPose=(source:T.Object3D,target:T.Object3D)=>{target.position.copy(source.position);target.quaternion.copy(source.quaternion);target.scale.copy(source.scale);source.children.forEach((child,i)=>{if(target.children[i])syncPose(child,target.children[i])})};
 const copies=new Map<T.Object3D,T.Object3D>();
 function update(){ground.position.y=WORLD_RADIUS-bus.position.length()-.002;bus.updateWorldMatrix(true,false);root.matrix.copy(bus.matrixWorld);const n=bus.position.clone().normalize(),f=new T.Vector3(1,0,0).applyQuaternion(bus.quaternion),r=new T.Vector3(0,0,1).applyQuaternion(bus.quaternion);groundMapping.update(n,f,r);oceanMapping.update(n,f,r);ocean.position.y=WORLD_RADIUS+SEA_LEVEL-bus.position.length();
 const groundPositions=ground.geometry.attributes.position;for(let i=0;i<groundPositions.count;i++){const dir=groundDirection(groundXY[i*3],-groundXY[i*3+1],n,f,r);groundPositions.setZ(i,terrainElevation(Math.atan2(dir.z,dir.x),Math.asin(dir.y)));}groundPositions.needsUpdate=true;
const project=(p:T.Vector3)=>projectRoadPoint(p,n,f,r,WORLD_RADIUS,bus.position.length());
 const output=geo.attributes.position,roadNormals=geo.attributes.normal;
 // Reuse vectors and update flat road normals directly: no per-triangle arrays or normal rebuild.
 for(let i=0;i<output.count;i+=3){let valid=true;for(let k=0;k<3;k++){const j=(i+k)*3,x=sourceRoad[j],y=sourceRoad[j+1],z=sourceRoad[j+2],len=Math.hypot(x,y,z);if((x*n.x+y*n.y+z*n.z)/len<.40)valid=false;}
 for(let k=0;k<3;k++){if(valid){const j=(i+k)*3,x=sourceRoad[j],y=sourceRoad[j+1],z=sourceRoad[j+2],len=Math.hypot(x,y,z),nx=x/len,ny=y/len,nz=z/len,cos=T.MathUtils.clamp(nx*n.x+ny*n.y+nz*n.z,-1,1),tx=nx-cos*n.x,ty=ny-cos*n.y,tz=nz-cos*n.z,tangent=Math.hypot(tx,ty,tz),scale=tangent>1e-10?Math.acos(cos)*WORLD_RADIUS/tangent:0;output.setXYZ(i+k,(tx*f.x+ty*f.y+tz*f.z)*scale,len-bus.position.length(),(tx*r.x+ty*r.y+tz*r.z)*scale);}else output.setXYZ(i+k,0,-200,0);roadNormals.setXYZ(i+k,0,1,0);}}
 output.needsUpdate=true;roadNormals.needsUpdate=true;
 dashes.forEach((d,i)=>{const route=Math.floor(i/ROAD_DASHES),t=(i%ROAD_DASHES)/ROAD_DASHES*Math.PI*2,p=pos(t,roadLatitude(t,route),WORLD_RADIUS+.055+route*.0001);d.visible=p.clone().normalize().dot(n)>.40&&!(roadJunction(t,route));if(d.visible){d.position.copy(project(p));const ahead=project(pos(t+.005,roadLatitude(t+.005,route),WORLD_RADIUS+.055+route*.0001)).sub(d.position);d.rotation.y=-Math.atan2(ahead.z,ahead.x)}});
 for(const source of globe.children){if(!(source instanceof T.Group)||source===bus)continue;if(copies.has(source)&&copies.get(source)!.userData.visualRevision!==source.userData.visualRevision){const old=copies.get(source)!;root.remove(old);old.traverse(o=>{if(o instanceof T.SkinnedMesh)o.skeleton.dispose()});copies.delete(source)}if(!copies.has(source)){if(!source.userData.projectGeometry&&source.position.clone().normalize().dot(n)<.65)continue;const copy:T.Object3D=source.userData.createRoadCopy?source.userData.createRoadCopy():source.userData.animatedTree?cloneRig(source):source.clone(true);if(source.userData.groundedVegetation)source.children.forEach((child,i)=>{const target=copy.children[i];if(child instanceof T.Mesh&&target instanceof T.Mesh){target.customDepthMaterial=child.customDepthMaterial;if(child.geometry.hasAttribute('groundOffset')){target.geometry=child.geometry.clone();const positions=target.geometry.attributes.position,offset=target.geometry.attributes.groundOffset;for(let j=0;j<positions.count;j++)positions.setY(j,positions.getY(j)-offset.getX(j));positions.needsUpdate=true;target.geometry.computeVertexNormals()}}});if(source.userData.projectGeometry)copy.children.forEach(o=>{if(o instanceof T.LineSegments){o.geometry=o.geometry.clone();o.frustumCulled=false}});if(source.userData.streetLamp){const light=copy.getObjectByName('Street lamp light') as T.SpotLight;light.target=copy.getObjectByName('Street lamp aim')!;}root.add(copy);copies.set(source,copy)}}
 for(const [source,copy] of copies){if(source.userData.projectGeometry){copy.visible=true;source.children.forEach((o,index)=>{if(!(o instanceof T.LineSegments))return;const target=copy.children[index] as T.LineSegments;const input=o.geometry.attributes.position,output=target.geometry.attributes.position;for(let i=0;i<input.count;i+=2){const a=new T.Vector3().fromBufferAttribute(input,i),b=new T.Vector3().fromBufferAttribute(input,i+1);const visible=a.clone().normalize().dot(n)>.1&&b.clone().normalize().dot(n)>.1;for(const [k,p] of [a,b].entries()){const v=visible?project(p):new T.Vector3(0,-200,0);output.setXYZ(i+k,v.x,v.y,v.z)}}output.needsUpdate=true});continue}copy.visible=globe.children.includes(source)&&source.position.clone().normalize().dot(n)>.65;if(!copy.visible)continue;copy.position.copy(project(source.position));const dir=new T.Vector3(0,0,1).applyQuaternion(source.quaternion);copy.quaternion.setFromAxisAngle(new T.Vector3(0,1,0),Math.atan2(dir.dot(f),dir.dot(r)));if(source.userData.wind)copy.rotateZ(Math.sin(performance.now()*.0015+source.id)*.02);copy.scale.copy(source.scale);if(source.userData.buildingLights){const original=source.getObjectByName('Night porch light') as T.PointLight,light=copy.getObjectByName('Night porch light') as T.PointLight;light.intensity=original.intensity;light.visible=original.visible;}if(source.userData.streetLamp){const original=source.getObjectByName('Street lamp light') as T.SpotLight,light=copy.getObjectByName('Street lamp light') as T.SpotLight;light.intensity=original.intensity;light.visible=original.visible;light.castShadow=original.castShadow;}if(source.userData.animatedChildren)source.children.forEach((child,i)=>{const target=copy.children[i];if(target){if(source.userData.animatedTree){syncPose(child,target);return}target.quaternion.copy(child.quaternion);target.position.copy(child.position);target.scale.copy(child.scale)}})}
 }
 return {setVisible(v:boolean){if(root.visible===v)return;root.visible=v;for(const o of globe.children)if(o!==bus)o.visible=!v;if(v)update()},update,dispose(){scene.remove(root);for(const [source,copy] of copies){copy.traverse(o=>{if(o instanceof T.SkinnedMesh)o.skeleton.dispose()});if(source.userData.streetLamp)(copy.getObjectByName('Street lamp light') as T.SpotLight).dispose();if(source.userData.groundedVegetation)copy.children.forEach(o=>{if(o instanceof T.Mesh&&o.geometry.hasAttribute('groundOffset'))o.geometry.dispose()});if(source.userData.projectGeometry)copy.children.forEach(o=>{if(o instanceof T.LineSegments)o.geometry.dispose()});}geo.dispose();ocean.geometry.dispose();ocean.material.dispose();ground.geometry.dispose();(ground.material as T.Material).dispose();(road.material as T.Material[]).forEach(m=>m.dispose());dashGeo.dispose();dashMat.dispose()}};
}
